name: ailingo

services:
  db:
    image: postgres:16
    container_name: ailingo_db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=ailingo
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "11002:5432"
    labels:
      io.portainer.accesscontrol.teams: dev,prod

  redis:
    image: redis:latest
    container_name: ailingo_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    labels:
      io.portainer.accesscontrol.teams: dev,prod

  backend-prod: &backend
    build:
      context: ..
    depends_on:
      - db
      - redis
    container_name: ailingo
    restart: unless-stopped
    labels:
      io.portainer.accesscontrol.teams: dev
    profiles:
      - prod
    environment:
      - CHAT_TOKEN=${CHAT_TOKEN}
      - JWT_SECRET=${JWT_SECRET}
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PROTOCOL=${SERVER_PROTOCOL}
      - SERVER_WEBSOCKET_PROTOCOL=${SERVER_WEBSOCKET_PROTOCOL}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ailingo
      - SPRING_DATASOURCE_USERNAME=ailingo
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_MAIL_USERNAME=${MAIL_USERNAME}
      - SPRING_MAIL_APP_PASSWORD=${MAIL_APP_PASSWORD}
      - SPRING_MAIL_HOST=smtp.mail.ru
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    ports:
      - "11001:8080"

  backend-dev:
    <<: *backend
    container_name: ailingo-dev
    profiles:
      - dev
    ports:
      - "8080:8080"
