chat:
  token: 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

server:
  servlet:
    context-path: /ailingo
  error:
    include-message: always
  host: localhost:8080
  protocol: http
  websocket:
    protocol: ws

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
    url: jdbc:postgresql://localhost:5432/lingo
    username: lingo
    password: lingo

  mail:
    host: mail.artux.net
    password: Lvwk7XsCUlbu3UBf
    port: 587
    properties:
      mail:
        smtp:
          auth: true
    protocol: smtp
    username: noreply@artux.net
  boot:
    admin:
      client:
        username: admin
        password: password
        url: http://localhost:8080

registration:
  confirmation:
    enabled: false
jwt:
  secret:
    key: secret
