server:
  servlet:
    context-path: /ailingo
  error:
    include-message: always
  host: localhost:8080
  protocol: http
  websocket:
    protocol: ws

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/lingo
    username: lingo
    password: lingo
    hikari:
      auto-commit: false
  boot:
    admin:
      client:
        username: admin
        password: password
        url: http://localhost:8080
  data:
    redis:
      port: 6379
      host: localhost
  mail:
    host: smtp.mail.ru
    port: 587
    username: letuchiy111@mail.ru
    password: yDFThjF1kz2dNrji5HdX
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

registration:
  confirmation:
    enabled: false
  allowed-emails:
    - vangelnum@gmail.com
    - q2w34132@gmail.com
    - laiven937@mail.ru
    - maks02_10@mail.ru
    - ariefymchenco@gmail.com

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration:
    900000
  refresh-token:
    expiration: 172800000