server:
  servlet:
    context-path: /ailingo
  error:
    include-message: always
  host: localhost:8080
  protocol: http
  websocket:
    protocol: ws

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/lingo
    username: lingo
    password: lingo
    hikari:
      auto-commit: false
  boot:
    admin:
      client:
        username: admin
        password: password
        url: http://localhost:8080

registration:
  confirmation:
    enabled: false