server:
  servlet:
    context-path: /ailingo
  error:
    include-message: always
  host: localhost:8080
  protocol: http
  websocket:
    protocol: ws

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/lingo
    username: lingo
    password: lingo
    hikari:
      auto-commit: false
  boot:
    admin:
      client:
        username: admin
        password: password
        url: http://localhost:8080

registration:
  confirmation:
    enabled: false
  allowed-emails:
    - vangelnum@gmail.com
    - q2w34132@gmail.com
    - laiven937@mail.ru
    - maks02_10@mail.ru
    - ariefymchenco@gmail.com

jwt:
  secret: ${JWT_SECRET}
  expiration:
    900000
  refresh-token:
    expiration: 172800000