create table if not exists app_user
(
    coins          integer,
    receive_emails boolean default true,
    streak         integer,
    xp             integer,
    last_login_at  timestamp(6) with time zone,
    last_session   timestamp(6) with time zone,
    registration   timestamp(6) with time zone,
    id             uuid not null
        primary key,
    avatar         varchar(255),
    email          varchar(255)
        unique,
    login          varchar(255)
        unique,
    name           varchar(255),
    password       varchar(255)
);

create table if not exists chat_history
(
    timestamp    timestamp(6),
    id           uuid         not null
        primary key,
    user_id      uuid         not null
        constraint fkad7p08x3hem1ha4aggmiaqrgx
            references app_user,
    chat_content varchar(255) not null
);

create table if not exists saved_topics
(
    id      bigint generated by default as identity
        primary key,
    user_id uuid
        constraint fkakng61c71avcf6uue3epygt02
            references app_user
);

create table if not exists topic
(
    level integer,
    price integer,
    id    bigint generated by default as identity
        primary key,
    image varchar(255),
    name  varchar(255)
);

create table if not exists user_saved_topics
(
    saved_topics_id bigint not null
        constraint fk9mbrw3muq1bux9lny0xvmwefw
            references saved_topics,
    topic_id        bigint not null
        constraint fk7vf589afja2e9emypvlm5u8yx
            references topic,
    primary key (saved_topics_id, topic_id)
);

create table if not exists user_entity_favorite_words
(
    user_entity_id uuid not null
        constraint fk65cxsv8ucu8ew46n1oe2x61n3
            references app_user,
    favorite_words varchar(255)
);

