name: CI/CD Master

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    name: 'Build and upload artifact'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'gradle'

      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.4

      - run: ./gradlew build --no-daemon -x test

      - name: Run services
        env:
          CHAT_TOKEN: ${{secrets.CHAT_TOKEN}}
          SERVER_HOST: app.artux.net

        run: |
          docker compose pull
          docker compose down
          docker compose up --profile prod -d
          docker system prune -a -f
        
