name: Test

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: 'Test artifact'
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '20'
          cache: 'gradle'

      - name: Test with Gradle
        run: ./gradlew test --stacktrace -x detekt